// Production-export interaction checks. Chain fixtures never ship in dist/.
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import {chromium} from 'playwright';
import {fixture,BASE,DIST,NFT,POOL} from './rpc-fixture.mjs';
const root=resolve(import.meta.dirname,'..'),out=resolve(root,'artifacts');await mkdir(out,{recursive:true});
const report={at:new Date().toISOString(),data:'Deterministic fixtures, including one hour per block for the fee-window boundary tests',checks:[],errors:[],resources:[]};
const check=(name,details='passed')=>{report.checks.push({name,details});console.log('PASS',name,typeof details==='string'?details:JSON.stringify(details));};
const server=createServer(async(req,res)=>{try{const file=req.url.replace(/^\/preview\//,'')||'index.html';if(!['index.html','swarm.js','ethers.umd.min.js','favicon.svg','screenshot.png'].includes(file))throw Error();res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.svg':'image/svg+xml','.png':'image/png'})[extname(file)]);res.end(await readFile(resolve(root,'dist',file)));}catch{res.writeHead(404).end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}/preview/`;let browser;
try{
 browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||undefined});
 const context=await browser.newContext({viewport:{width:1440,height:900}}),chain=fixture();chain.blockSeconds=3600;
 chain.log('RewardsReceived',[240000000000000000n,4000000000000000000n],BASE-5,0);
 chain.log('RewardsReceived',[480000000000000000n,0],BASE-2,0);
 chain.log('RewardsReceived',[120000000000000000n,0],BASE-24,0);
 chain.log('RewardsReceived',[9000000000000000000n,0],BASE-25,0);
 await context.route('https://**/*',chain.route);
 await context.addInitScript(()=>{
   window.noticeRequests=0;window.notices=[];window.copied=[];window.soundStarts=0;
   const NativeAudioContext=window.AudioContext;window.AudioContext=class extends NativeAudioContext {createOscillator(){const oscillator=super.createOscillator(),start=oscillator.start.bind(oscillator);oscillator.start=(...args)=>{window.soundStarts++;return start(...args);};return oscillator;}};
   window.Notification=class {static permission='default';static async requestPermission(){window.noticeRequests++;this.permission='granted';return 'granted';}constructor(title,options){window.notices.push({title,...options});}close(){}};
   Object.defineProperty(navigator,'clipboard',{value:{writeText:async v=>window.copied.push(v)},configurable:true});
 });
 const page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));page.on('requestfailed',r=>report.resources.push(r.url()));
 await page.goto(url);await page.waitForFunction(()=>window.__swarm?.ready);
 assert.equal(chain.calls.filter(c=>c.method==='eth_getLogs').length,0);check('new tools do not add startup history scans');
 const open=async id=>{await page.locator(`[data-open="${id}"]`).click();assert(await page.locator('#'+id).isVisible());};
 await open('calculator');await page.waitForFunction(()=>document.querySelector('#feeStatus').textContent.includes('24h ordinary fees:'),null,{timeout:60000});
 assert((await page.locator('#feeStatus').textContent()).includes('0.84 ETH'));check('24h window includes boundary, excludes older event and all surplus');
 const rows=async id=>(await page.locator(`#${id} td`).allTextContents()).map(Number);
 let values=await rows('calcFees');assert(Math.abs(values[0]-.84/70/24)<.0000006);assert(Math.abs(values[1]-.84/70)<.0000006);assert(Math.abs(values[2]-.84/70*30)<.0000006);
 await page.selectOption('#calcLevel','3');await page.selectOption('#calcFrom','2');assert((await page.locator('#calcUpgrade').innerText()).startsWith('250,000 OG'));assert.equal(await page.locator('#calcWeight').textContent(),'4');assert.equal(await page.locator('#calcBurn').textContent(),'400,000 OG');
 values=await rows('calcFees');assert(Math.abs(values[1]-.84/70*4)<.0000006);assert((await page.locator('#calcPayback').innerText()).includes('days'));
 const cost=400000/(2**28);assert(Math.abs(parseFloat(await page.locator('#calcCost').innerText())-cost)<.0000006);check('L3 weight, pool spot cost, cumulative burn, upgrade difference, hour/day/30-day fees and payback');
 await page.selectOption('#calcLevel','1');assert((await page.locator('#calcUpgrade').innerText()).includes('equal or higher'));
 await page.fill('#calcAccount','garbage');await page.locator('#calcLookup button').click();assert.equal(await page.locator('#calcAccount').getAttribute('aria-invalid'),'true');
 await page.fill('#calcAccount','2');await page.locator('#calcLookup button').click();assert((await page.locator('#calcLookupResult').innerText()).includes('Pepe #2 · L2'));assert.equal(await page.locator('#calcFrom').inputValue(),'2');
 await page.fill('#calcAccount',DIST);await page.locator('#calcLookup button').click();assert((await page.locator('#calcLookupResult').innerText()).includes('10 active Pepes · L1: 10'));assert((await page.locator('#calcLookupResult').innerText()).includes('14.285714%'));
 await page.fill('#calcAccount','35');await page.locator('#calcLookup button').click();await page.waitForFunction(()=>document.querySelector('#calcLookupResult').textContent.includes('Inactive (level 0)'));check('invalid input, active Pepe, wallet aggregation/share and inactive Pepe lookup');
 await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('data-open')),'calculator');check('desktop tool Escape restores trigger focus');
 await open('contracts');assert.equal(await page.locator('.contract-row').count(),6);for(const b of await page.locator('.contract-row button').all())await b.click();const copied=await page.evaluate(()=>window.copied);assert.equal(new Set(copied).size,6);assert(copied.includes(POOL));assert((await page.locator('#copyStatus').textContent()).includes('Pool ID copied'));check('all six copy controls copy full address or pool ID; Etherscan links present');await page.evaluate(()=>navigator.clipboard.writeText=async()=>{throw new Error('Blocked');});await page.locator('.contract-row button').first().click();assert((await page.locator('#copyStatus').innerText()).includes('is selected'));assert.equal(await page.evaluate(()=>getSelection().toString()),copied[0]);check('clipboard denial selects complete value and explains manual copying');
 await open('how');assert.equal(await page.locator('#how a').getAttribute('href'),'https://og.sites.imd.fun');assert.equal(await page.locator('.glossary dt').count(),9);check('glossary and official site accessible');
 await open('alerts');assert.equal(await page.evaluate(()=>window.noticeRequests),0);await page.check('#alertEnabled');await page.check('#alertSound');await page.check('#alertSwap');await page.fill('#alertThreshold','.05');await page.locator('#alertForm button[type=submit]').click();await page.locator('#enableNotifications').click();assert.equal(await page.evaluate(()=>window.noticeRequests),1);check('notification permission requested only by explicit click');
 const step=async mutate=>{mutate();chain.head++;await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await page.waitForFunction(h=>document.querySelector('#blk').textContent.includes(h.toLocaleString('en-US')),chain.head,{timeout:20000});};
 await step(()=>chain.log('Swap',[POOL,DIST,-(10n**17n),10n**22n,2n**96n,1000,0,3000],chain.head+1,0));assert((await page.locator('#toastStack').innerText()).includes('Big buy: 0.1 ETH'));assert.equal((await page.evaluate(()=>window.notices)).length,1);assert((await page.evaluate(()=>window.soundStarts))>0);check('big-swap threshold triggers toast, opted-in notification and native audio oscillator');
 const toastCount=await page.locator('.toast').count();await step(()=>chain.log('Swap',[POOL,DIST,-(10n**16n),10n**21n,2n**96n,1000,0,3000],chain.head+1,0));assert.equal(await page.locator('.toast').count(),toastCount);check('swaps below threshold do not alert');
 await page.selectOption('#alertScope','ids');await page.fill('#alertIds','1, nope');await page.locator('#alertForm button[type=submit]').click();assert.equal(await page.locator('#alertIds').getAttribute('aria-invalid'),'true');await page.fill('#alertIds','1');await page.locator('#alertForm button[type=submit]').click();
 await step(()=>{chain.population[0].level=2;chain.log('Upgraded',[1,DIST,1,2,100000],chain.head+1,0);chain.log('AuctionListed',[2,100000,1800000000],chain.head+1,1);});assert((await page.locator('#toastStack').innerText()).includes('Pepe #1 upgraded'));assert(!(await page.locator('#toastStack').innerText()).includes('Pepe #2'));check('specific-ID filtering and invalid ID list validation');
 await page.fill('#hlAddr',DIST);await page.locator('#hlAddr').dispatchEvent('change');await page.selectOption('#alertScope','wallet');await page.locator('#alertForm button[type=submit]').click();
 await step(()=>{chain.population=chain.population.filter(n=>n.id!==1);chain.log('Exited',[1,DIST,123000000000000000n],chain.head+1,0);chain.log('AuctionListed',[1,50000000000000000000000n,1800000000],chain.head+1,1);});assert((await page.locator('#toastStack').innerText()).includes('New auction: Pepe #1'));assert((await page.locator('#toastStack').innerText()).includes('Pepe #1 exited'));check('wallet exit and verified AuctionListed correlate by token and transaction');
 await step(()=>{chain.population.push({id:31,owner:NFT.toLowerCase(),level:1,pending:0n,last:1800000000});chain.log('Activated',[31,NFT,1,50000],chain.head+1,0);});assert(!(await page.locator('#toastStack').innerText()).includes('#31'));check('unrelated wallet activation excluded');
 await step(()=>chain.log('Swap',[POOL,NFT,-(10n**17n),10n**22n,2n**96n,1000,0,3000],chain.head+1,0));for(let i=0;i<50&&!chain.calls.some(c=>c.method==='eth_getTransactionByHash');i++)await page.waitForTimeout(100);assert(chain.calls.some(c=>c.method==='eth_getTransactionByHash'));check('wallet swap uses transaction sender, not pool router field');
 await page.reload();await page.waitForFunction(()=>window.__swarm?.ready);await open('alerts');assert.equal(await page.locator('#alertScope').inputValue(),'wallet');assert(await page.locator('#alertEnabled').isChecked());assert.equal(await page.evaluate(()=>window.noticeRequests),0);assert.equal(await page.locator('.toast').count(),0);check('preferences persist; reload requests no notification permission and replays no old alerts');
 for(const [width,height] of [[320,640],[375,812],[430,932],[812,375],[768,800],[1024,768],[1440,900]]){
  await page.setViewportSize({width,height});await page.waitForTimeout(150);
  const mobile=await page.evaluate(()=>window.__swarm.view().mobile);
  for(const id of ['calculator','how','alerts','contracts']){
   if(mobile){await page.locator('#btnMenu').click();await page.locator(`[data-open="${id}"]`).click();}else {if(!(await page.locator('#'+id).isVisible()))await open(id);}
   assert(await page.locator('#'+id).isVisible());
   const geometry=await page.evaluate(id=>{const panel=document.querySelector('#'+id),rect=panel.getBoundingClientRect();return {overflow:document.documentElement.scrollWidth>innerWidth,left:rect.left,right:rect.right,internal:panel.scrollWidth>panel.clientWidth+1};},id);assert(!geometry.overflow&&!geometry.internal,`${width}x${height} ${id}: ${JSON.stringify(geometry)}`);assert(geometry.left>=0&&geometry.right<=width);
   if(mobile){await page.locator('#sheetPanels').evaluate(e=>e.scrollTop=e.scrollHeight);const visibleEnd=await page.evaluate(id=>document.querySelector('#'+id).getBoundingClientRect().bottom<=document.querySelector('#sheetPanels').getBoundingClientRect().bottom+1,id);assert(visibleEnd);}
  }
  check(`four tools fit and remain scrollable at ${width}x${height}`);
  if(width===375||width===1440)await page.screenshot({path:resolve(out,`tools-contracts-${width}.png`),scale:'css'});
 }
 await page.setViewportSize({width:375,height:812});if(await page.locator('#sheetToggle').getAttribute('aria-expanded')==='false')await page.locator('#sheetToggle').click();await page.locator('#tabStats').click();await page.locator('#tabStats').focus();await page.keyboard.press('End');assert.equal(await page.evaluate(()=>document.activeElement.id),'tabContracts');await page.keyboard.press('Home');assert.equal(await page.evaluate(()=>document.activeElement.id),'tabStats');check('seven-tab keyboard Home/End navigation');
 await page.locator('#tabCalculator').click();await page.locator('#sheetPanels').evaluate(e=>e.scrollTop=0);await page.screenshot({path:resolve(out,'tools-calculator-mobile.png'),scale:'css'});
 await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('.dot').evaluate(e=>getComputedStyle(e).animationName),'none');check('reduced-motion status CSS');
 const contrast=await page.locator('#calculator').evaluate(panel=>{const rgb=s=>s.match(/[\d.]+/g).slice(0,3).map(Number),lum=c=>c.map(v=>(v/=255)<=.04045?v/12.92:((v+.055)/1.055)**2.4).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0);const bg=lum(rgb(getComputedStyle(panel).backgroundColor));return [...panel.querySelectorAll('.help')].slice(0,3).map(el=>{const fg=lum(rgb(getComputedStyle(el).color));return {color:getComputedStyle(el).color,background:getComputedStyle(panel).backgroundColor,ratio:(Math.max(fg,bg)+.05)/(Math.min(fg,bg)+.05)};});});assert(contrast.every(c=>c.ratio>4.5));check('rendered opaque panel secondary-text contrast',contrast);
 assert(chain.calls.filter(c=>c.method==='eth_getLogs').every(c=>Number(c.params[0].toBlock)-Number(c.params[0].fromBlock)<50));assert.equal(chain.maxHttp,1);check('history and alerts retain serialized requests and 50-block log bounds');
 assert.deepEqual(report.errors,[]);assert.deepEqual(report.resources,[]);check('no application errors or failed resources with deterministic RPC');await context.close();
 const edgeContext=await browser.newContext({viewport:{width:1280,height:800}}),edge=fixture();edge.blockSeconds=3600;edge.streamSeconds=1800;
 await edgeContext.route('https://**/*',edge.route);const ep=await edgeContext.newPage();ep.on('pageerror',e=>report.errors.push(e.message));
 await ep.goto(url);await ep.waitForFunction(()=>window.__swarm?.ready);await ep.locator('[data-open="calculator"]').click();await ep.waitForFunction(()=>document.querySelector('#feeStatus').textContent.includes('24h ordinary fees:'),null,{timeout:60000});
 const capped=(await ep.locator('#calcStream td').allTextContents()).map(Number);assert(capped.every(n=>n>0&&n<=1/70+.0000006));assert(capped.every(n=>n===capped[0]));assert((await ep.locator('#feeStatus').textContent()).includes('0 ETH'));check('zero-event window is a real zero; backlog projections stop at stream end');
 const expectedPayback=(50000/2**28)/capped[1];assert(Math.abs(parseFloat(await ep.locator('#calcPayback').innerText())-expectedPayback)<.0000006);check('payback divides by the displayed capped ETH/day');
 let before=edge.calls.length;await ep.reload();await ep.waitForFunction(()=>window.__swarm?.ready);await ep.locator('[data-open="calculator"]').click();await ep.waitForFunction(()=>document.querySelector('#feeStatus').textContent.includes('24h ordinary fees:'));assert.equal(edge.calls.slice(before).filter(c=>c.method==='eth_getLogs').length,0);check('completed historical chunks are reused after reload');
 await ep.evaluate(()=>localStorage.clear());edge.population=[];edge.streamSeconds=0;await ep.reload();await ep.waitForFunction(()=>window.__swarm?.ready);await ep.locator('[data-open="calculator"]').click();await ep.waitForFunction(()=>document.querySelector('#feeStatus').textContent.includes('24h ordinary fees:'),null,{timeout:60000});assert((await ep.locator('#calcPayback').innerText()).includes('No finite payback'));assert((await ep.locator('#calcPerWeight').innerText()).includes('No active weight'));assert(!(await ep.locator('#calculator').innerText()).match(/NaN|Infinity/));check('zero-weight, stopped-stream and no-payback states');
 await ep.evaluate(()=>localStorage.clear());let failOnce=true;edge.fail=c=>failOnce&&c.method==='eth_getLogs'?(failOnce=false,{status:429}):null;await ep.reload();await ep.waitForFunction(()=>window.__swarm?.ready);await ep.locator('[data-open="calculator"]').click();await ep.waitForFunction(()=>document.querySelector('#feeStatus').textContent.includes("Can't load"),null,{timeout:60000});assert((await ep.locator('#calcTotal').innerText()).includes('Retrying'));assert((await ep.locator('#rpcMessage').innerText()).includes("Can't reach Ethereum RPC"));await ep.locator('#rpcRetry').click();await ep.waitForFunction(()=>document.querySelector('#feeStatus').textContent.includes('24h ordinary fees:'),null,{timeout:40000});check('fee history 429 shows incomplete state, Retry respects cooldown and recovers');
 assert.deepEqual(report.errors,[]);await edgeContext.close();report.result='passed';
}catch(e){report.result='failed';report.failure=e.stack;console.error(e);process.exitCode=1;}finally{await writeFile(resolve(out,'tools-results.json'),JSON.stringify(report,null,2)+'\n');await browser?.close();await new Promise(r=>server.close(r));}
